[tasks.boids]
script = "cargo run --bin boids-example"
dependencies = ["clippy", "test", "fmt"]

[tasks.neutonian]
script = "cargo run --bin neutonian"
dependencies = ["clippy", "test", "fmt"]

[tasks.turret]
script = "cargo run --bin turret_combat"
dependencies = ["clippy", "test", "fmt"]

[tasks.build-all]
script = "cargo build --release"
dependencies = ["clippy", "test", "fmt"]

[tasks.fmt]
script = "cargo fmt"
