name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main
      - 'feature-**'

jobs:
  test_apps:
    strategy:
      matrix:
        project: ['boids', 'neutonian']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy

      - uses: Swatinem/rust-cache@v2
        name: Setup Cargo cache
        with:
          workspaces: ${{ matrix.project }} -> target
          key: ${{ matrix.project }}

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cd ${{ matrix.project }}
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: |
          cd ${{ matrix.project }}
          cargo check
